[package]
name = "rspoa"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.15.4"
clap = { version = "3.1.5", features = ["derive"] }
project-root = "0.2.2"

